import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const dictionary = {
  en: {
    // Brand & Header
    appTitle: "Krushi Dhara",
    appBadge: "AI",
    appSubtitle: "Smart Plant Doctor & Voice Assistant",
    navHome: "Home",
    navDashboard: "Farmer Dashboard",
    navDoctor: "AI Plant Doctor",
    navWeather: "Weather Alert",
    navSchemes: "Govt Schemes",
    navShops: "Nearby Shops",
    navHistory: "Scan History",
    navDiagrams: "Architecture & Diagrams",
    navExpert: "Expert Panel",
    navAdmin: "Admin Panel",
    navLogin: "Login / Register",
    navLogout: "Logout",
    roleFarmer: "Farmer",
    roleExpert: "Agri Expert",
    roleAdmin: "Admin",

    // Hero Section
    heroBadge: "✨ Smart Plant Doctor & Voice Assistant",
    heroTitleLine1: "Protect Your Crops with",
    heroTitleLine2: "AI & Voice Intelligence",
    heroSubtitle: "Take a photo of leaf, fruit, stem or flower or speak in Marathi, Hindi or English. Get instant AI disease diagnosis, organic remedies and government approved medicines.",
    heroCtaDoctor: "🩺 Diagnose Crop →",
    heroCtaVoice: "🎙️ Voice Assistant (Hindi/Marathi/EN)",
    heroCheck1: "98.4% AI Accuracy",
    heroCheck2: "Organic & Chemical Remedies",
    heroCheck3: "Govt Scheme Finder",
    heroCheck4: "ICAR Expert Verification",

    // Features Section
    featuresTitle: "Comprehensive Smart Agriculture Suite",
    featuresSub: "Everything a farmer needs to diagnose diseases, calculate weather risks, search schemes, and increase crop yields.",
    feat1Title: "AI Plant Doctor Engine",
    feat1Desc: "Instantly detect crop diseases with 98.4% accuracy across Leaf, Fruit, Stem & Flower images using deep learning vision algorithms.",
    feat2Title: "Multilingual Voice Assistant",
    feat2Desc: "Speak your crop symptoms directly in Hindi, Marathi, or English. Powered by OpenAI Whisper Speech-to-Text.",
    feat3Title: "Weather & Disease Risk Forecast",
    feat3Desc: "Predict fungal and pest disease outbreaks up to 7 days in advance based on humidity, rainfall, and thermal metrics.",
    feat4Title: "Govt Approved Treatments",
    feat4Desc: "Access organic bio-remedies and ICAR government-approved chemical pesticides with exact dosage guidelines.",
    feat5Title: "Nearby Shop & Krishi Kendra Locator",
    feat5Desc: "Locate nearest licensed fertilizer shops, pesticide stores, and Krishi Vigyan Kendras with map navigation.",
    feat6Title: "1-on-1 Expert Tele-Consultation",
    feat6Desc: "Get your AI diagnoses reviewed by verified Senior Agricultural Pathologists with direct expert messaging.",

    // Stats
    stat1: "Farmers Empowered",
    stat2: "AI Diagnostic Accuracy",
    stat3: "Crop Diseases Covered",
    stat4: "Estimated Crop Loss Saved",

    // Testimonials
    testimonialsTitle: "Trusted by Farmers across India",
    testimonialsSub: "Real feedback from sugarcane, tomato, and wheat growers",
    testimonial1: "The Marathi voice assistant helped me identify tomato disease instantly. My crop recovered in 5 days!",
    testimonial2: "KrishiMitra AI diagnosed Yellow Rust in my wheat crop before it spread. Saved over ₹80,000 in yield loss!",
    testimonial3: "The organic remedy guide combined with nearby shop locator is fantastic. Highly recommended for every farmer.",

    // FAQ
    faqTitle: "Frequently Asked Questions",
    faq1Q: "How does the AI Plant Doctor work?",
    faq1A: "Simply snap or upload a photo of your affected crop leaf, fruit, or stem. Our computer vision model identifies the exact disease, severity, organic treatments, and chemical remedies in 3 seconds.",
    faq2Q: "Does it support local Indian languages?",
    faq2A: "Yes! KrishiMitra AI supports full voice and text in Hindi (हिंदी), Marathi (मराठी), and English.",
    faq3Q: "Are the suggested medicines government approved?",
    faq3A: "All chemical treatment recommendations are cross-verified with ICAR standards and state agricultural ministry guidelines.",
    faq4Q: "Is KrishiMitra AI free for farmers?",
    faq4A: "Yes! All core disease detection, voice assistance, weather risk alerts, and government scheme lookups are 100% free for farmers.",

    // Bottom CTA
    ctaTitle: "Ready to Protect Your Harvest?",
    ctaSub: "Join over 45,000 farmers using AI to diagnose crop diseases and maximize their yield today.",
    ctaBtn: "Launch AI Plant Doctor Now",

    // Dashboard
    dashTitle: "Farmer Command Center",
    dashWelcome: "Welcome back",
    dashLocation: "Location Not Specified (Update Profile)",
    dashNewScan: "+ New Crop Scan",
    dashVoiceCmd: "Voice Command",
    metricTotalDiagnoses: "Total Diagnoses",
    metricHealthyPlants: "Healthy Plants",
    metricDiseasedPlants: "Diseased Plants",
    metricModelAccuracy: "AI Model Accuracy",
    metricMonthGrowth: "+14 this month",
    metricTotalScans: "75.6% of total crop scans",
    metricActiveTreatment: "12 active in treatment",
    metricVerified: "Verified by ICAR Pathology",
    weatherAlertTitle: "High Disease Risk Warning",
    weatherAlertSub: "Regional Weather Alert: 84% Relative Humidity",
    weatherAlertDesc: "High moisture levels increase Late Blight fungal spore germination on tomatoes by 40% in next 48 hours.",
    weatherAlertBtn: "View Weather Risk Report",
    chartMonthlyTrend: "Monthly Crop Diagnostics Trend",
    chartMonthlySub: "Total plant scans vs disease detection instances",
    chartDiseaseBreakdown: "Disease Type Breakdown",
    chartDiseaseSub: "Distribution of identified crop pathogens",
    recentDiagnosesTitle: "Recent Crop Diagnoses",
    viewFullHistory: "View Full History →",
    quickActionsTitle: "Quick Actions",
    quickAction1Title: "Upload Crop Leaf Photo",
    quickAction1Desc: "Instant AI diagnosis & medicines",
    quickAction2Title: "Government Schemes",
    quickAction2Desc: "Find subsidies & crop insurance",
    quickAction3Title: "Find Nearby Pesticide Shop",
    quickAction3Desc: "Locate closest Krishi Kendra",

    // Plant Doctor Page
    doctorTitle: "AI Plant Doctor & Disease Detector",
    doctorSub: "Upload photo of Leaf, Fruit, Stem, or Flower. AI will detect disease, severity, organic solutions & medicines in seconds.",
    step1Title: "1. Upload Crop Image (AI Auto-Detects Crop)",
    step2Title: "2. Select Plant Part",
    aiDetectedCropLabel: "AI Auto-Detected Crop:",
    manualCropOverride: "Manual Crop Override:",
    partLeaf: "Leaf 🍃",
    partFruit: "Fruit 🍎",
    partStem: "Stem 🪵",
    partFlower: "Flower 🌸",
    uploadPrompt: "Click or drag & drop crop image",
    uploadFormats: "Supports JPG, PNG, WEBP (Max 15MB)",
    btnAnalyze: "Analyze Image with AI",
    btnAnalyzing: "Running AI Vision Model...",
    samplePrompt: "Or click sample leaf photo for instant test:",
    outcomeTitle: "AI Diagnosis Outcome",
    symptomsTitle: "Identified Symptoms",
    causesTitle: "Root Causes",
    organicTitle: "🍃 Organic Bio-Remedies",
    chemicalTitle: "🧪 Chemical Pesticides & Brand Medicines",
    recommendedBrands: "Recommended Brands:",
    expectedRecovery: "Expected Recovery:",
    daysText: "Days with proper treatment",
    btnDownloadPdf: "Download PDF Report",

    // Weather Page
    agrometTag: "Automated Agromet Advisory",
    weatherTitle: "Weather & Disease Risk Forecast",
    weatherSub: "Real-time microclimate weather insights synchronized with your profile location.",
    syncedFromProfile: "Synced from Profile",
    liveFeedActive: "Live Weather Feed Active",
    forecastForDistrict: "Forecast for District",
    tempLabel: "Temperature",
    feelsLike: "Feels like",
    humidityLabel: "Relative Humidity",
    sporeThreshold: "High spore threshold",
    rainLabel: "Rain Forecast",
    windLabel: "Wind Velocity",
    sporeTransport: "Spore wind transport",
    sporeRiskTitle: "Fungal Spore Risk Calculation",
    riskAlertTitle: "High Disease Risk Alert for Next 48h",
    riskLevelHigh: "RISK LEVEL: HIGH",
    vulnerableCrops: "Crops Vulnerable Right Now:",
    predictedOutbreaks: "Predicted Pathogen Outbreaks:",
    agriAdvisory: "Agricultural Advisory:",
    outlook5Day: "5-Day Agricultural Weather Outlook",
    humidityWord: "Humidity",

    // Govt Schemes Page
    subsidiesTag: "Government Subsidies & Insurance",
    schemesTitle: "Government Schemes Explorer",
    schemesSub: "Discover and apply for central & state government agricultural welfare schemes.",
    searchSchemePlaceholder: "Search schemes by name, crop or benefit...",
    allStates: "All States",
    allCategories: "All Categories",
    financialBenefits: "Financial Benefits:",
    eligibilityCriteria: "Eligibility Criteria:",
    targetCropsLabel: "Target Crops:",
    stateLabelShort: "State:",
    helplineLabel: "Helpline:",
    btnApplyPortal: "Apply Portal",

    // Nearby Shops Page
    geoFinderTag: "Geo-Targeted Agri Store Finder",
    shopsTitle: "Nearby Agri Shops & Krishi Kendras",
    shopsSub: "Locate closest licensed fertilizer stores, pesticide dealers, and Krishi Vigyan Kendras.",
    searchShopPlaceholder: "Search by store name, medicine (e.g. Ridomil, Nano Urea, Trichoderma, Drip)...",
    mapTitle: "Live Location Map",
    gpsActive: "GPS Active",
    availableStock: "Available Stock in Store:",
    btnDirections: "Get Directions",
    allCategoriesShops: "All Categories (12 Shops)",
    sortNearest: "Nearest",
    sortRating: "Rating",
    mapPinVisualizer: "Google Map Pin Visualizer",
    pinsSynced: "12 Pins Synced",
    googleMapsApiMode: "Google Maps API Mode",
    fromYourFarm: "from your farm in",
    getDirectionsBtn: "Get Google Maps Directions",
    searchAllGoogleMaps: "Search all nearby pesticide & fertilizer shops on Google Maps",
    showingStoresCount: "Showing verified stores near",
    allShopsVerified: "✓ All 12 shops verified with Google Maps links",
    govtLicensed: "Govt Licensed",
    availableInStock: "Available In Stock:",
    openInGoogleMaps: "Open in Google Maps",

    // History Page
    historyTitle: "Crop Disease History & Log",
    historySub: "Track recovery progress, view past AI diagnoses, and export PDF reports.",
    searchHistoryPlaceholder: "Search disease or crop...",
    colCropImage: "Crop & Image",
    colDisease: "Detected Disease",
    colMetrics: "Confidence & Severity",
    colDate: "Date",
    colStatus: "Recovery Status",
    colActions: "PDF & Actions",
    statusInTreatment: "In Treatment",
    statusRecovered: "Recovered",
    statusDetected: "Detected",
    statusLost: "Crop Lost",

    // Profile Page
    profileTitle: "Farmer Profile Settings",
    profileSub: "Manage your farm parameters to get personalized disease advisories.",
    profileBannerTag: "Farmer Dashboard Profile",
    profileHeaderTitle: "Farmer Registration & Parameters",
    profileHeaderSub: "Complete your profile information to receive AI-driven soil insights, government scheme eligibility matching, and hyper-local crop advisories.",
    profileSetupMeter: "Profile Setup",
    personalInfoSection: "Personal Information",
    personalInfoSub: "Basic identification details of the farmer",
    farmerIdLabel: "Farmer ID (Auto-generated):",
    regenerateId: "Regenerate",
    verifiedAadhaar: "✓ Verified Aadhaar Linked",
    fullNameLabel: "Full Name",
    genderLabel: "Gender",
    dobLabel: "Date of Birth",
    ageText: "yrs",
    mobileLabel: "Mobile Number",
    emailLabel: "Email Address",
    addressSection: "📍 Address Information",
    addressSub: "Location details for accurate localized weather & mandi price predictions",
    stateLabel: "State",
    districtLabel: "District",
    talukaLabel: "Taluka / Tehsil",
    villageLabel: "Village",
    pincodeLabel: "PIN Code",
    farmInfoSection: "🌾 Farm Information",
    farmInfoSub: "Land metrics, soil taxonomy, irrigation sources, and water tables",
    landAreaLabel: "Total Land Area",
    plotsLabel: "Number of Farm Plots",
    soilTypeLabel: "Soil Type (Black, Red, Sandy, Loamy, Clay)",
    irrigationLabel: "Irrigation Source (Well, Borewell, Canal, Drip, Rain-fed)",
    waterLevelLabel: "Water Availability (Low, Medium, High)",
    primaryCropsLabel: "Primary Crops Grown",
    voiceSettingsSection: "Language & Voice Settings",
    preferredLangLabel: "Preferred Language for Voice & Diagnosis Advisories",
    saveProfileBtn: "Save Profile",
    saveSuccessMsg: "All profile information saved successfully!",
    secPersonal: "1. Personal Information",
    secFarm: "2. Farm & Agriculture Details",
    secPreferences: "3. Language & App Preferences",
    lblFullName: "Full Name",
    lblPhone: "Phone Number",
    lblFarmSize: "Total Farm Size (Acres)",
    lblSoilType: "Soil Type",
    lblCrops: "Primary Crops Grown",
    lblDistrictState: "District / State",
    btnSaveProfile: "Save Changes",
    profileSaved: "Profile updated successfully!",

    // Voice Modal & Chatbot
    voiceModalTitle: "Multilingual Voice Assistant",
    voiceModalSub: "Speak your crop problem in your preferred native language",
    micListening: "🎙️ Listening... Speak now clearly",
    micIdle: "Click microphone to start speaking",
    transcriptLabel: "Speech Transcript",
    btnSendDoctor: "Send to Plant Doctor",
    chatbotTitle: "KrishiMitra AI Bot",
    chatbotSub: "Powered by OpenAI GPT Agritech Expert Model",
    chatbotPlaceholder: "Ask AI about fertilizers, symptoms, watering...",

    // Footer
    footerDesc: "Smart Plant Doctor powered by AI image recognition, multilingual voice assistant (Hindi, Marathi, English), and agricultural expert network.",
    footerApproved: "Govt of India Agritech Approved",
    kisanCallCenter: "National Kisan Call Center",
    tollFree: "1800-180-1551"
  },

  hi: {
    // Brand & Header
    appTitle: "कृषिधारा",
    appBadge: "AI",
    appSubtitle: "स्मार्ट फसल डॉक्टर और वॉइस असिस्टेंट",
    navHome: "मुख्य पृष्ठ",
    navDashboard: "किसान डैशबोर्ड",
    navDoctor: "AI फसल डॉक्टर",
    navWeather: "मौसम अलर्ट",
    navSchemes: "सरकारी योजनाएं",
    navShops: "निकटतम दुकानें",
    navHistory: "जांच इतिहास",
    navDiagrams: "सिस्टम आर्किटेक्चर",
    navExpert: "विशेषज्ञ पैनल",
    navAdmin: "एडमिन पैनल",
    navLogin: "लॉगिन / पंजीकरण",
    navLogout: "लॉगआउट",
    roleFarmer: "किसान",
    roleExpert: "कृषि विशेषज्ञ",
    roleAdmin: "एडमिन",

    // Hero Section
    heroBadge: "✨ स्मार्ट फसल डॉक्टर और वॉइस असिस्टेंट",
    heroTitleLine1: "AI और आवाज़ की मदद से",
    heroTitleLine2: "अपनी फसलों की सुरक्षा करें",
    heroSubtitle: "पत्ते, फल, तने या फूल की फोटो खींचें अथवा हिंदी, मराठी या अंग्रेजी में बोलें। तुरंत प्राप्त करें AI बीमारी निदान, जैविक उपाय और सरकारी दवाएं।",
    heroCtaDoctor: "<ctrl42> फसल जांचें →",
    heroCtaVoice: "🎙️ वॉइस असिस्टेंट (Hindi/Marathi/EN)",
    heroCheck1: "98.4% AI सटीकता",
    heroCheck2: "जैविक व रासायनिक उपचार",
    heroCheck3: "सरकारी योजना खोजक",
    heroCheck4: "ICAR विशेषज्ञ सत्यापन",

    // Features Section
    featuresTitle: "संपूर्ण स्मार्ट कृषि सुइट",
    featuresSub: "किसान को बीमारी पहचानने, मौसम जोखिम, योजनाएं खोजने और फसल उत्पादन बढ़ाने के लिए सब कुछ।",
    feat1Title: "AI फसल डॉक्टर इंजन",
    feat1Desc: "पत्ते, फल, तने और फूल की फोटो से 98.4% सटीकता के साथ तुरंत बीमारी पहचानें।",
    feat2Title: "बहुभाषी वॉइस असिस्टेंट",
    feat2Desc: "हिंदी, मराठी या अंग्रेजी में सीधे अपनी फसल की समस्या बोलें। OpenAI Whisper द्वारा संचालित।",
    feat3Title: "मौसम व बीमारी जोखिम पूर्वानुमान",
    feat3Desc: "आर्द्रता, वर्षा और तापमान के आधार पर 7 दिन पहले बीमारी के प्रकोप की भविष्यवाणी करें।",
    feat4Title: "सरकारी अनुमोदित उपचार",
    feat4Desc: "ICAR अनुमोदित जैविक और रासायनिक कीटनाशकों की सटीक खुराक जानकारी प्राप्त करें।",
    feat5Title: "निकटतम दुकान व कृषि केंद्र",
    feat5Desc: "नज़दीकी लाइसेंस प्राप्त उर्वरक स्टोर, कीटनाशक दुकान और कृषि विज्ञान केंद्र खोजें।",
    feat6Title: "1-on-1 विशेषज्ञ परामर्श",
    feat6Desc: "वरिष्ठ कृषि रोगविज्ञानियों द्वारा AI निदान की समीक्षा करवाएं।",

    // Stats
    stat1: "किसान सशक्त",
    stat2: "AI निदान सटीकता",
    stat3: "फसल रोग कवर",
    stat4: "अनुमानित फसल हानि बचाई",

    // Testimonials
    testimonialsTitle: "भारत भर के किसानों का विश्वास",
    testimonialsSub: "गन्ना, टमाटर और गेहूं उगाने वाले किसानों की वास्तविक प्रतिक्रिया",
    testimonial1: "मराठी वॉइस असिस्टेंट से मुझे टमाटर की बीमारी तुरंत पता चली। 5 दिन में फसल ठीक हो गई!",
    testimonial2: "KrishiMitra AI ने मेरे गेहूं में Yellow Rust फैलने से पहले पकड़ लिया। ₹80,000 की फसल बची!",
    testimonial3: "जैविक उपाय गाइड और निकटतम दुकान लोकेटर बहुत उपयोगी है। हर किसान के लिए अनुशंसित।",

    // FAQ
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    faq1Q: "AI फसल डॉक्टर कैसे काम करता है?",
    faq1A: "बस अपनी प्रभावित फसल के पत्ते, फल या तने की फोटो अपलोड करें। हमारा AI मॉडल 3 सेकंड में बीमारी, गंभीरता और उपचार बताएगा।",
    faq2Q: "क्या यह भारतीय भाषाओं को सपोर्ट करता है?",
    faq2A: "हाँ! KrishiMitra AI हिंदी, मराठी और अंग्रेजी में पूर्ण वॉइस और टेक्स्ट सपोर्ट करता है।",
    faq3Q: "क्या सुझाई गई दवाएं सरकारी अनुमोदित हैं?",
    faq3A: "सभी रासायनिक उपचार ICAR मानकों और राज्य कृषि मंत्रालय दिशानिर्देशों के अनुसार हैं।",
    faq4Q: "क्या KrishiMitra AI किसानों के लिए मुफ्त है?",
    faq4A: "हाँ! सभी मुख्य सुविधाएं — बीमारी पहचान, वॉइस असिस्टेंट, मौसम अलर्ट और योजना खोज — किसानों के लिए 100% मुफ्त हैं।",

    // Bottom CTA
    ctaTitle: "अपनी फसल की सुरक्षा के लिए तैयार हैं?",
    ctaSub: "आज ही 45,000+ किसानों के साथ जुड़ें जो AI से फसल रोग पहचान रहे हैं।",
    ctaBtn: "AI फसल डॉक्टर शुरू करें",

    // Dashboard
    dashTitle: "किसान कमांड सेंटर",
    dashWelcome: "नमस्ते",
    dashLocation: "नासिक जिला, महाराष्ट्र • 4.5 एकड़ खेती",
    dashNewScan: "+ नई फसल जांच",
    dashVoiceCmd: "वॉइस कमान्ड",
    metricTotalDiagnoses: "कुल जांच",
    metricHealthyPlants: "स्वस्थ पौधे",
    metricDiseasedPlants: "रोगग्रस्त पौधे",
    metricModelAccuracy: "AI मॉडल सटीकता",
    metricMonthGrowth: "+14 इस महीने",
    metricTotalScans: "कुल जांचों का 75.6%",
    metricActiveTreatment: "12 उपचार में सक्रिय",
    metricVerified: "ICAR पैथोलॉजी द्वारा सत्यापित",
    weatherAlertTitle: "उच्च बीमारी जोखिम चेतावनी",
    weatherAlertSub: "नासिक मौसम अलर्ट: 84% आर्द्रता",
    weatherAlertDesc: "उच्च नमी के कारण अगले 48 घंटों में टमाटर पर लेट ब्लाइट कवक का प्रसार 40% बढ़ जाता है।",
    weatherAlertBtn: "मौसम जोखिम रिपोर्ट देखें",
    chartMonthlyTrend: "मासिक फसल जांच रुझान",
    chartMonthlySub: "कुल फसल स्कैन बनाम बीमारी मिलने के मामले",
    chartDiseaseBreakdown: "बीमारी प्रकार विभाजन",
    chartDiseaseSub: "पहचाने गए रोगजनकों का वितरण",
    recentDiagnosesTitle: "हाल की फसल जांचें",
    viewFullHistory: "पूरा इतिहास देखें →",
    quickActionsTitle: "त्वरित कार्य",
    quickAction1Title: "फसल के पत्ते की फोटो अपलोड करें",
    quickAction1Desc: "तुरंत AI बीमारी निदान व दवाएं",
    quickAction2Title: "सरकारी योजनाएं",
    quickAction2Desc: "सब्सिडी और फसल बीमा खोजें",
    quickAction3Title: "निकटतम कीटनाशक दुकान खोजें",
    quickAction3Desc: "नज़दीकी कृषि केंद्र का पता लगाएं",

    // Plant Doctor Page
    doctorTitle: "AI फसल डॉक्टर और रोग पहचानकर्ता",
    doctorSub: "पत्ते, फल, तने या फूल की फोटो अपलोड करें। AI सेकंडों में बीमारी, गंभीरता, जैविक उपाय और दवाएं बताएगा।",
    step1Title: "1. फसल की फोटो अपलोड करें (AI स्वतः फसल पहचानेगा)",
    step2Title: "2. पौधे का भाग चुनें",
    aiDetectedCropLabel: "AI द्वारा पहचानी गई फसल:",
    manualCropOverride: "खुद फसल चुनें (मैनुअल बदलाव):",
    partLeaf: "पत्ता 🍃",
    partFruit: "फल 🍎",
    partStem: "तना 🪵",
    partFlower: "फूल 🌸",
    uploadPrompt: "फसल की फोटो क्लिक करें या ड्रैग-ड्रॉप करें",
    uploadFormats: "JPG, PNG, WEBP समर्थित (अधिकतम 15MB)",
    btnAnalyze: "AI द्वारा फोटो जांचें",
    btnAnalyzing: "AI विज़न मॉडल चल रहा है...",
    samplePrompt: "या तुरंत परीक्षण के लिए नमूना फोटो पर क्लिक करें:",
    outcomeTitle: "AI निदान परिणाम",
    symptomsTitle: "पहचाने गए लक्षण",
    causesTitle: "मुख्य कारण",
    organicTitle: "🍃 जैविक बायो-उपचार",
    chemicalTitle: "🧪 रासायनिक कीटनाशक व ब्रांड दवाएं",
    recommendedBrands: "अनुशंसित ब्रांड:",
    expectedRecovery: "अनुमानित सुधार काल:",
    daysText: "उचित उपचार से दिन",
    btnDownloadPdf: "PDF रिपोर्ट डाउनलोड करें",

    // Weather Page
    agrometTag: "स्वचालित एग्रोमेट परामर्श",
    weatherTitle: "मौसम व बीमारी जोखिम पूर्वानुमान",
    weatherSub: "आपकी प्रोफाइल स्थिति के साथ सिंक्रनाइज़ वास्तविक समय मौसम पूर्वानुमान।",
    syncedFromProfile: "प्रोफाइल से लिंक",
    liveFeedActive: "लाइव मौसम फीड सक्रिय",
    forecastForDistrict: "जिला पूर्वानुमान",
    tempLabel: "तापमान",
    feelsLike: "महसूस होता है",
    humidityLabel: "सापेक्ष आर्द्रता",
    sporeThreshold: "उच्च बीजाणु प्रसार जोखिम",
    rainLabel: "वर्षा पूर्वानुमान",
    windLabel: "हवा की गति",
    sporeTransport: "बीजाणु पवन परिवहन",
    sporeRiskTitle: "कवक बीजाणु जोखिम गणना",
    riskAlertTitle: "अगले 48 घंटों के लिए उच्च रोग जोखिम चेतावनी",
    riskLevelHigh: "जोखिम स्तर: उच्च",
    vulnerableCrops: "इस समय संवेदनशील फसलें:",
    predictedOutbreaks: "संभावित बीमारी प्रकोप:",
    agriAdvisory: "कृषि परामर्श सलाह:",
    outlook5Day: "5-दिवसीय कृषि मौसम पूर्वानुमान",
    humidityWord: "आर्द्रता",

    // Govt Schemes Page
    subsidiesTag: "सरकारी सब्सिडी व फसल बीमा",
    schemesTitle: "सरकारी योजनाएं एक्सप्लोरर",
    schemesSub: "केंद्र व राज्य सरकार की कृषि कल्याण योजनाओं की जानकारी प्राप्त करें और आवेदन करें।",
    searchSchemePlaceholder: "नाम, फसल या लाभ से योजना खोजें...",
    allStates: "सभी राज्य",
    allCategories: "सभी श्रेणियां",
    financialBenefits: "वित्तीय लाभ:",
    eligibilityCriteria: "पात्रता मानदंड:",
    targetCropsLabel: "लक्षित फसलें:",
    stateLabelShort: "राज्य:",
    helplineLabel: "हेल्पलाइन:",
    btnApplyPortal: "आवेदन पोर्टल",

    // Nearby Shops Page
    shopsTitle: "निकटतम कृषि दुकानें व केंद्र",
    shopsSub: "नज़दीकी लाइसेंस प्राप्त उर्वरक स्टोर, कीटनाशक डीलर और कृषि विज्ञान केंद्र (KVK) खोजें।",
    searchShopPlaceholder: "दुकान का नाम या दवा का नाम खोजें (उदा. रिडोमिल गोल्ड)...",
    mapTitle: "लाइव लोकेशन मैप (नासिक)",
    gpsActive: "GPS सक्रिय",
    availableStock: "दुकान में उपलब्ध स्टॉक:",
    btnDirections: "रास्ता (दिशा) देखें",

    // History Page
    historyTitle: "फसल बीमारी जांच इतिहास",
    historySub: "सुधार की प्रगति को ट्रैक करें, पुराने AI निदान देखें और PDF रिपोर्ट निर्यात करें।",
    searchHistoryPlaceholder: "बीमारी या फसल खोजें...",
    colCropImage: "फसल व फोटो",
    colDisease: "पहचाना गया रोग",
    colMetrics: "सटीकता व गंभीरता",
    colDate: "दिनांक",
    colStatus: "सुधार स्थिति",
    colActions: "PDF व कार्य",
    statusInTreatment: "उपचार जारी",
    statusRecovered: "पूर्ण स्वस्थ",
    statusDetected: "पहचाना गया",
    statusLost: "फसल क्षति",

    // Profile Page
    profileTitle: "किसान प्रोफाइल सेटिंग्स",
    profileSub: "व्यक्तिगत बीमारी सलाह प्राप्त करने के लिए अपने खेत के विवरण दर्ज करें।",
    secPersonal: "1. व्यक्तिगत जानकारी",
    secFarm: "2. खेत व कृषि विवरण",
    secPreferences: "3. भाषा व ऐप प्राथमिकताएं",
    lblFullName: "पूरा नाम",
    lblPhone: "फोन नंबर",
    lblFarmSize: "कुल खेत का आकार (एकड़)",
    lblSoilType: "मिट्टी का प्रकार",
    lblCrops: "उगाई जाने वाली मुख्य फसलें",
    lblDistrictState: "जिला / राज्य",
    btnSaveProfile: "विवरण सहेजें",
    profileSaved: "प्रोफाइल सफलतापूर्वक अपडेट हो गई!",

    // Voice Modal & Chatbot
    voiceModalTitle: "बहुभाषी वॉइस असिस्टेंट",
    voiceModalSub: "अपनी फसल की समस्या अपनी मातृभाषा में बोलकर बताएं",
    micListening: "🎙️ सुन रहा हूँ... स्पष्ट रूप से बोलें",
    micIdle: "बोलने के लिए माइक्रोफोन दबाएं",
    transcriptLabel: "बोली गई आवाज का पाठ",
    btnSendDoctor: "फसल डॉक्टर को भेजें",
    chatbotTitle: "कृषि मित्र AI बोट",
    chatbotSub: "OpenAI GPT कृषि विशेषज्ञ मॉडल द्वारा संचालित",
    chatbotPlaceholder: "खाद, लक्षण, सिंचाई के बारे में AI से पूछें...",

    // Footer
    footerDesc: "AI इमेज रिकग्निशन, बहुभाषी वॉइस असिस्टेंट (हिंदी, मराठी, अंग्रेजी) और कृषि विशेषज्ञ नेटवर्क द्वारा संचालित स्मार्ट फसल डॉक्टर।",
    footerApproved: "भारत सरकार एग्रीटेक अनुमोदित",
    kisanCallCenter: "राष्ट्रीय किसान कॉल सेंटर",
    tollFree: "1800-180-1551"
  },

  mr: {
    // Brand & Header
    appTitle: "कृषिधारा",
    appBadge: "AI",
    appSubtitle: "स्मार्ट वनस्पती डॉक्टर आणि व्हॉईस असिस्टंट",
    navHome: "मुख्य पान",
    navDashboard: "शेतकरी डॅशबोर्ड",
    navDoctor: "AI वनस्पती डॉक्टर",
    navWeather: "हवामान इशारा",
    navSchemes: "शासकीय योजना",
    navShops: "जवळची दुकाने",
    navHistory: "तपासणी इतिहास",
    navDiagrams: "सिस्टम आर्किटेक्चर",
    navExpert: "तज्ज्ञ पॅनेल",
    navAdmin: "अ‍ॅडमिन पॅनेल",
    navLogin: "लॉगिन / नोंदणी",
    navLogout: "लॉगआउट",
    roleFarmer: "शेतकरी",
    roleExpert: "कृषी तज्ज्ञ",
    roleAdmin: "अ‍ॅडमिन",

    // Hero Section
    heroBadge: "✨ स्मार्ट वनस्पती डॉक्टर आणि व्हॉईस असिस्टंट",
    heroTitleLine1: "AI आणि आवाजाच्या साहाय्याने",
    heroTitleLine2: "आपल्या पिकांचे रक्षण करा",
    heroSubtitle: "पाने, फळे, खोड किंवा फुलाचा फोटो काढा किंवा मराठी, हिंदी किंवा इंग्रजीत बोला. मिळवा झटपट AI रोग निदान, सेंद्रिय उपाय आणि शासकीय औषधे.",
    heroCtaDoctor: "🩺 पीक तपासा →",
    heroCtaVoice: "🎙️ व्हॉईस असिस्टंट (Hindi/Marathi/EN)",
    heroCheck1: "98.4% AI अचूकता",
    heroCheck2: "सेंद्रिय आणि रासायनिक उपाय",
    heroCheck3: "शासकीय योजना शोधक",
    heroCheck4: "तज्ज्ञ पडताळणी",

    // Features Section
    featuresTitle: "संपूर्ण स्मार्ट शेती सुइट",
    featuresSub: "शेतकऱ्याला रोग निदान, हवामान धोका, योजना शोध आणि पीक उत्पादन वाढवण्यासाठी सर्व काही.",
    feat1Title: "AI पीक डॉक्टर इंजिन",
    feat1Desc: "पान, फळ, खोड आणि फुलाच्या फोटोवरून 98.4% अचूकतेने झटपट रोग ओळखा.",
    feat2Title: "बहुभाषिक व्हॉईस असिस्टंट",
    feat2Desc: "मराठी, हिंदी किंवा इंग्रजीत थेट पिकाची समस्या सांगा. OpenAI Whisper द्वारे संचलित.",
    feat3Title: "हवामान आणि रोग धोका अंदाज",
    feat3Desc: "आर्द्रता, पाऊस आणि तापमानावर आधारित 7 दिवस आधी रोगाचा प्रादुर्भाव सांगा.",
    feat4Title: "शासन मान्य उपचार",
    feat4Desc: "ICAR मान्यताप्राप्त सेंद्रिय आणि रासायनिक कीटकनाशकांची अचूक मात्रा माहिती मिळवा.",
    feat5Title: "जवळचे दुकान व कृषी केंद्र",
    feat5Desc: "जवळचे अधिकृत खत विक्रेते, कीटकनाशक दुकाने आणि कृषी विज्ञान केंद्र शोधा.",
    feat6Title: "1-on-1 तज्ज्ञ सल्लामसलत",
    feat6Desc: "वरिष्ठ कृषी रोगशास्त्रज्ञांकडून AI निदानाची पडताळणी करून घ्या.",

    // Stats
    stat1: "शेतकरी सक्षम",
    stat2: "AI निदान अचूकता",
    stat3: "पीक रोग समाविष्ट",
    stat4: "अंदाजे पीक नुकसान वाचवले",

    // Testimonials
    testimonialsTitle: "भारतभरातील शेतकऱ्यांचा विश्वास",
    testimonialsSub: "ऊस, टोमॅटो आणि गहू उत्पादकांचा खरा अभिप्राय",
    testimonial1: "मराठी व्हॉईस असिस्टंटमुळे मला टोमॅटोच्या रोगाची लगेच माहिती मिळाली. ५ दिवसात माझे पीक पूर्ववत झाले!",
    testimonial2: "KrishiMitra AI ने माझ्या गव्हातील Yellow Rust पसरण्यापूर्वी ओळखला. ₹80,000 चे नुकसान वाचले!",
    testimonial3: "सेंद्रिय उपाय मार्गदर्शिका आणि जवळचे दुकान शोधक खूप उपयुक्त आहे. प्रत्येक शेतकऱ्यासाठी शिफारस.",

    // FAQ
    faqTitle: "वारंवार विचारले जाणारे प्रश्न",
    faq1Q: "AI पीक डॉक्टर कसे काम करते?",
    faq1A: "फक्त बाधित पिकाच्या पान, फळ किंवा खोडाचा फोटो अपलोड करा. आमचे AI मॉडेल 3 सेकंदात रोग, तीव्रता आणि उपचार सांगेल.",
    faq2Q: "हे भारतीय भाषांना समर्थन देते का?",
    faq2A: "होय! KrishiMitra AI मराठी, हिंदी आणि इंग्रजीत पूर्ण व्हॉईस आणि मजकूर समर्थन देते.",
    faq3Q: "सुचवलेली औषधे शासन मान्य आहेत का?",
    faq3A: "सर्व रासायनिक उपचार ICAR मानके आणि राज्य कृषी मंत्रालय मार्गदर्शक तत्त्वांनुसार आहेत.",
    faq4Q: "KrishiMitra AI शेतकऱ्यांसाठी मोफत आहे का?",
    faq4A: "होय! रोग निदान, व्हॉईस असिस्टंट, हवामान इशारे आणि योजना शोध — सर्व शेतकऱ्यांसाठी 100% मोफत.",

    // Bottom CTA
    ctaTitle: "तुमच्या पिकाचे संरक्षण करण्यास तयार आहात?",
    ctaSub: "आज 45,000+ शेतकऱ्यांसोबत सामील व्हा जे AI ने पीक रोग ओळखत आहेत.",
    ctaBtn: "AI पीक डॉक्टर सुरू करा",

    // Dashboard
    dashTitle: "शेतकरी कमांड सेंटर",
    dashWelcome: "नमस्कार",
    dashLocation: "नाशिक जिल्हा, महाराष्ट्र • 4.5 एकर शेती",
    dashNewScan: "+ नवीन पीक तपासणी",
    dashVoiceCmd: "व्हॉईस कमांड",
    metricTotalDiagnoses: "एकूण तपासण्या",
    metricHealthyPlants: "निरोगी पिके",
    metricDiseasedPlants: "बाधित पिके",
    metricModelAccuracy: "AI मॉडेल अचूकता",
    metricMonthGrowth: "+14 या महिन्यात",
    metricTotalScans: "एकूण तपासण्यांपैकी 75.6%",
    metricActiveTreatment: "12 उपचारात सक्रिय",
    metricVerified: "ICAR पॅथॉलॉजी द्वारे प्रमाणित",
    weatherAlertTitle: "उच्च रोग धोक्याचा इशारा",
    weatherAlertSub: "नाशिक हवामान इशारा: 84% आर्द्रता",
    weatherAlertDesc: "आर्द्रतेचे प्रमाण जास्त असल्यामुळे पुढील 48 तासांत टोमॅटोवर करपा (Late Blight) बुरशीचा प्रादुर्भाव 40% ने वाढू शकतो.",
    weatherAlertBtn: "हवामान धोका अहवाल पहा",
    chartMonthlyTrend: "मासिक पीक तपासणी कल",
    chartMonthlySub: "एकूण स्कॅन विरुद्ध रोग आढळलेली उदाहरणे",
    chartDiseaseBreakdown: "रोग प्रकार विभागणी",
    chartDiseaseSub: "आढळलेल्या रोगजंतूंचे प्रमाण",
    recentDiagnosesTitle: "नुकत्याच केलेल्या पीक तपासण्या",
    viewFullHistory: "पूर्ण इतिहास पहा →",
    quickActionsTitle: "जलद कृती",
    quickAction1Title: "पिकाच्या पानाचा फोटो अपलोड करा",
    quickAction1Desc: "झटपट AI रोग निदान व औषधे",
    quickAction2Title: "शासकीय योजना",
    quickAction2Desc: "अनुदाने आणि पीक विमा शोधा",
    quickAction3Title: "जवळचे कीटकनाशक दुकान शोधा",
    quickAction3Desc: "जवळच्या कृषी केंद्राचा पत्ता मिळवा",

    // Plant Doctor Page
    doctorTitle: "AI वनस्पती डॉक्टर आणि रोग शोधक",
    doctorSub: "पान, फळ, खोड किंवा फुलाचा फोटो अपलोड करा. AI काही सेकंदात रोग, तीव्रता, सेंद्रिय उपाय आणि औषधे सांगेल.",
    step1Title: "1. पिकाचा फोटो अपलोड करा (AI स्वतः पीक ओळखेल)",
    step2Title: "2. रोपाचा भाग निवडा",
    aiDetectedCropLabel: "AI द्वारे ओळखलेले पीक:",
    manualCropOverride: "स्वतः पीक निवडा (मॅन्युअल बदल):",
    partLeaf: "पान 🍃",
    partFruit: "फळ 🍎",
    partStem: "खोड 🪵",
    partFlower: "फूल 🌸",
    uploadPrompt: "पिकाचा फोटो काढा किंवा ड्रॅग-ड्रॉप करा",
    uploadFormats: "JPG, PNG, WEBP समर्थित (जास्तीत जास्त 15MB)",
    btnAnalyze: "AI द्वारे फोटो तपासा",
    btnAnalyzing: "AI व्हिजन मॉडेल चालत आहे...",
    samplePrompt: "किंवा झटपट चाचणीसाठी नमुना फोटोवर क्लिक करा:",
    outcomeTitle: "AI निदान निकाल",
    symptomsTitle: "आढळलेली लक्षणे",
    causesTitle: "मुख्य कारणे",
    organicTitle: "🍃 सेंद्रिय बायो-उपाय",
    chemicalTitle: "🧪 रासायनिक कीटकनाशके व ब्रँड औषधे",
    recommendedBrands: "सुचवलेले ब्रँड:",
    expectedRecovery: "अपेक्षित सुधारणा काळ:",
    daysText: "योग्य उपचाराने दिवस",
    btnDownloadPdf: "PDF अहवाल डाउनलोड करा",

    // Weather Page
    agrometTag: "स्वयंचलित अ‍ॅग्रोमेट सल्ला",
    weatherTitle: "हवामान आणि रोग धोका अंदाज",
    weatherSub: "तुमच्या प्रोफाईल स्थानाशी जुळवून घेतलेला रिअल-टाईम हवामान अंदाज.",
    syncedFromProfile: "प्रोफाईलवरून जुळवले",
    liveFeedActive: "थेट हवामान फीड सुरू",
    forecastForDistrict: "जिल्ह्यासाठी अंदाज",
    tempLabel: "तापमान",
    feelsLike: "अंदाजे जाणवते",
    humidityLabel: "सापेक्ष आर्द्रता",
    sporeThreshold: "उच्च बीजाणू धोका पातळी",
    rainLabel: "पाऊस अंदाज",
    windLabel: "वाऱ्याचा वेग",
    sporeTransport: "बीजाणू वाहून नेणारा वारा",
    sporeRiskTitle: "बुरशीजन्य बीजाणू धोका गणना",
    riskAlertTitle: "पुढील 48 तासांसाठी उच्च रोग धोक्याचा इशारा",
    riskLevelHigh: "धोका पातळी: उच्च",
    vulnerableCrops: "सध्या संवेदनक्षम पिके:",
    predictedOutbreaks: "संभाव्य रोगाचा प्रादुर्भाव:",
    agriAdvisory: "कृषी सल्लागार मार्गदर्शन:",
    outlook5Day: "5-दिवसीय कृषी हवामान अंदाज",
    humidityWord: "आर्द्रता",

    // Govt Schemes Page
    subsidiesTag: "शासकीय अनुदाने आणि पीक विमा",
    schemesTitle: "शासकीय योजना एक्सप्लोरर",
    schemesSub: "केंद्र व राज्य शासनाच्या कृषी कल्याणकारी योजनांची माहिती मिळवा आणि अर्ज करा.",
    searchSchemePlaceholder: "नाव, पीक किंवा लाभाने योजना शोधा...",
    allStates: "सर्व राज्ये",
    allCategories: "सर्व वर्ग",
    financialBenefits: "आर्थिक लाभ:",
    eligibilityCriteria: "पात्रता निकष:",
    targetCropsLabel: "लक्ष्यित पिके:",
    stateLabelShort: "राज्य:",
    helplineLabel: "हेल्पलाइन:",
    btnApplyPortal: "अर्ज पोर्टल",

    // Nearby Shops Page
    geoFinderTag: "भू-स्थानिक कृषी दुकान शोधक",
    shopsTitle: "जवळची कृषी दुकाने व केंद्रे",
    shopsSub: "जवळचे अधिकृत खत विक्रेते, कीटकनाशक दुकाने आणि कृषी विज्ञान केंद्र (KVK) शोधा.",
    searchShopPlaceholder: "दुकानाचे नाव किंवा औषध शोधा (उदा. रिडोमिल, नॅनो युरिया)...",
    mapTitle: "लाइव्ह लोकेशन नकाशा",
    gpsActive: "GPS सक्रिय",
    availableStock: "दुकानात उपलब्ध साठा:",
    btnDirections: "रस्ता (दिशा) मिळवा",
    allCategoriesShops: "सर्व वर्ग (12 दुकाने)",
    sortNearest: "जवळचे",
    sortRating: "रेटिंग",
    mapPinVisualizer: "गूगल मॅप पिन व्हिज्युअलायझर",
    pinsSynced: "12 पिन जुळवल्या",
    googleMapsApiMode: "गूगल मॅप्स एपीआय मोड",
    fromYourFarm: "तुमच्या शेतापासून अंतर",
    getDirectionsBtn: "गूगल मॅप्सवर रस्ता मिळवा",
    searchAllGoogleMaps: "गूगल मॅप्सवर सर्व जवळची दुकाने शोधा",
    showingStoresCount: "प्रमाणित दुकाने जवळ",
    allShopsVerified: "✓ सर्व 12 दुकाने गूगल मॅप्स सह प्रमाणित",
    govtLicensed: "शासन मान्य",
    availableInStock: "दुकानात उपलब्ध साठा:",
    openInGoogleMaps: "गूगल मॅप्समध्ये उघडा",

    // History Page
    historyTitle: "पीक रोग तपासणी इतिहास",
    historySub: "सुधारणा प्रगतीचा मागोवा घ्या, जुने AI निदान पहा आणि PDF अहवाल डाउनलोड करा.",
    searchHistoryPlaceholder: "रोग किंवा पीक शोधा...",
    colCropImage: "पीक व फोटो",
    colDisease: "आढळलेला रोग",
    colMetrics: "अचूकता व तीव्रता",
    colDate: "दिनांक",
    colStatus: "सुधारणा स्थिती",
    colActions: "PDF व कृती",
    statusInTreatment: "उपचार सुरू",
    statusRecovered: "पूर्ण निरोगी",
    statusDetected: "निदान झाले",
    statusLost: "पीक नुकसान",

    // Profile Page
    profileTitle: "शेतकरी प्रोफाइल सेटिंग्ज",
    profileSub: "वैयक्तिक रोग सल्ला मिळवण्यासाठी तुमच्या शेताचे तपशील नोंदवा.",
    secPersonal: "1. वैयक्तिक माहिती",
    secFarm: "2. शेत व कृषी तपशील",
    secPreferences: "3. भाषा व अ‍ॅप प्राधान्ये",
    lblFullName: "पूर्ण नाव",
    lblPhone: "फोन नंबर",
    lblFarmSize: "एकूण शेताचे क्षेत्र (एकर)",
    lblSoilType: "मातीचा प्रकार",
    lblCrops: "घेतली जाणारी मुख्य पिके",
    lblDistrictState: "जिल्हा / राज्य",
    btnSaveProfile: "तपशील जतन करा",
    profileSaved: "प्रोफाईल यशस्वीरित्या अद्ययावत झाली!",

    // Voice Modal & Chatbot
    voiceModalTitle: "बहुभाषिक व्हॉईस असिस्टंट",
    voiceModalSub: "तुमची पिकाची समस्या तुमच्या मातृभाषेत बोलून सांगा",
    micListening: "🎙️ ऐकत आहे... स्पष्टपणे बोला",
    micIdle: "बोलण्यासाठी मायक्रोफोन दाबा",
    transcriptLabel: "बोललेल्या शब्दांचा मजकूर",
    btnSendDoctor: "पीक डॉक्टरकडे पाठवा",
    chatbotTitle: "कृषी मित्र AI बॉट",
    chatbotSub: "OpenAI GPT कृषी तज्ज्ञ मॉडेल द्वारे संचलित",
    chatbotPlaceholder: "खते, लक्षणे, सिंचनाबद्दल AI ला विचारा...",

    // Footer
    footerDesc: "AI इमेज रिकग्निशन, बहुभाषिक व्हॉईस असिस्टंट (हिंदी, मराठी, इंग्रजी) आणि कृषी तज्ज्ञ नेटवर्क द्वारे संचलित स्मार्ट वनस्पती डॉक्टर.",
    footerApproved: "भारत सरकार अ‍ॅग्रिटेक मान्यताप्राप्त",
    kisanCallCenter: "राष्ट्रीय किसान कॉल सेंटर",
    tollFree: "1800-180-1551"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('mr'); // Default to Marathi matching user screenshot!

  const t = (key) => {
    return dictionary[language]?.[key] || dictionary['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
