export const generatePDFReport = (diagnosis) => {
  const printWindow = window.open('', '_blank');
  
  const content = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>KrishiMitra AI - Plant Health & Diagnostic Report</title>
        <style>
          body { font-family: 'Helvetica Neue', Arial, sans-serif; margin: 30px; color: #1e293b; background: #fff; }
          .header { text-align: center; border-bottom: 3px solid #16a34a; padding-bottom: 15px; margin-bottom: 20px; }
          .title { font-size: 26px; color: #15803d; font-weight: bold; margin: 0; }
          .subtitle { font-size: 14px; color: #64748b; margin-top: 5px; }
          .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; background: #dcfce7; color: #15803d; font-weight: bold; font-size: 12px; }
          .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 20px; }
          .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; }
          h3 { color: #166534; font-size: 16px; border-bottom: 1px dashed #cbd5e1; padding-bottom: 6px; margin-top: 0; }
          ul { padding-left: 20px; margin: 5px 0; }
          li { font-size: 13px; line-height: 1.6; margin-bottom: 4px; }
          .footer { text-align: center; margin-top: 30px; font-size: 11px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">🌿 KRISHIMITRA AI – PLANT DOCTOR REPORT</div>
          <div class="subtitle">Official AI Crop Health Assessment & Treatment Plan</div>
          <p><strong>Report ID:</strong> ${diagnosis.id || 'KM-DIAG-2026'} | <strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        </div>

        <div class="card" style="margin-bottom: 20px; background: #f0fdf4;">
          <h2 style="margin: 0 0 10px 0; color: #14532d;">${diagnosis.detected_disease}</h2>
          <p><strong>Crop Name:</strong> ${diagnosis.crop_name} | <strong>Part Affected:</strong> ${diagnosis.plant_part || 'Leaf'}</p>
          <p>
            <span class="badge">Confidence: ${diagnosis.confidence_score}%</span>
            <span class="badge" style="background:#fee2e2; color:#991b1b;">Severity: ${diagnosis.severity}</span>
          </p>
        </div>

        <div class="grid">
          <div class="card">
            <h3>🔬 Symptoms Identified</h3>
            <ul>
              ${(diagnosis.symptoms || []).map(s => `<li>${s}</li>`).join('')}
            </ul>
          </div>
          <div class="card">
            <h3>🌱 Root Causes</h3>
            <ul>
              ${(diagnosis.causes || []).map(c => `<li>${c}</li>`).join('')}
            </ul>
          </div>
        </div>

        <div class="card" style="margin-bottom: 20px;">
          <h3>🍃 Recommended Organic Solutions</h3>
          <ul>
            ${(diagnosis.organic_treatment || []).map(t => `<li>${t}</li>`).join('')}
          </ul>
        </div>

        <div class="card" style="margin-bottom: 20px; background: #fff1f2;">
          <h3 style="color:#9f1239;">🧪 Government Approved Chemical Treatment</h3>
          <ul>
            ${(diagnosis.chemical_treatment || []).map(c => `<li>${c}</li>`).join('')}
          </ul>
          <p style="font-size:12px; color:#be123c;"><strong>Recommended Brand Medicines:</strong> ${(diagnosis.medicines || []).join(', ')}</p>
        </div>

        <div class="footer">
          <p>Generated by KrishiMitra AI Platform | Verified by Indian Council of Agricultural Research (ICAR) Dataset</p>
          <p>Helpline: 1800-180-1551 | Website: https://krishimitra.ai</p>
        </div>
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(content);
  printWindow.document.close();
};
